# Generated by Django 6.0.5 on 2026-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('electrico', 'Eléctrico'), ('mecanico', 'Mecánico'), ('hidraulico', 'Hidráulico'), ('neumatico', 'Neumático'), ('electronico', 'Electrónico')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_adquisicion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
